### ISSUE TITLE
MPL license for `min2phase` and others

### ISSUE THREAD

**Issue by lgarron** [cs0x7f/min2phase#17]
Hi @cs0x7f,

I've been working on new WCA-compatible scrambles in `cubing.js` [^1], where we're using your code under the GPL: https://github.com/cubing/cubing.js/tree/2f1f395f6bbdf0485de3b8524d038d56d6978580/src/cubing/vendor/gpl/cs0x7f

However, the GPL has several issues, including a prohibition that disallows anyone from using the code in an iOS app.

Would you be willing to license your relevant code (`min2phase`, `sq12phase`, and the 4x4x4 reduction solver from `cstimer`) under the MPL license?
It disallows private changes to the source code, while still allowing some private uses.

Thanks,
»Lucas

[^1]: With the ambitious goal of replacing TNoodle, among other things.

**Comment by cs0x7f** [comment]
After this commit (https://github.com/cs0x7f/TPR-4x4x4-Solver/commit/e432528210ddcc4fb75586a14163b172795caa9f), I added MIT license options for min2phase, TPR-4x4x4-Solver, sq12phase to make it easier for more users to use these solvers/scramblers.
